### ISSUE TITLE
Key Error radar_data.

### ISSUE THREAD

**Issue by Ainecop** [colindecourt/record#2]
Traceback (most recent call last):
  File "main_cruw.py", line 103, in <module>
    trainer.fit(model, ckpt_path=args.resume_ckpt)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1153, in _run_train
    self._run_sanity_check()
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1225, in _run_sanity_check
    val_loop.run()
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/necop/.local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/necop/hamza/record/executors/cruw_trainer.py", line 136, in validation_step
    ra_maps = batch['radar_data'] # N, H, W, C
KeyError: 'radar_data'

Any idea why is this error occuring. I am not able to trace batch to know why the radar_data is not present in it

**Comment by colindecourt** [comment]
Hi, I think there is an issue with the data you’re trying to load. Please check all the paths are correct and that you try to load the right data. See this issue for more Information: https://github.com/colindecourt/record/issues/1. 
Kind regards 
Colin

**Comment by Ainecop** [comment]
Yes, there was a mistake made while preparing the data. Thanks!
